Match data in db with data.json (#dawa-merchant#141)
dawa-io/country-region-data pull request #1
Opened 2023-06-28 10:49 UTC by miguelhormigo

## Description

- Match data in develop database with data.json from country-region-data.
- Add data comparer script

## Related Issue

(#dawa-merchant#141)

## How Has This Been Tested?

- [x] Manually
- [ ] Specs

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (update of libraries or refactor of code)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added an entry at the top of the CHANGELOG.md file documenting my changes.

2023-06-28 10:58 UTC, eliseo-dawa approved these changes
Looks good to me. Nice job 👍

2023-06-30 10:03 UTC, sjpatino approved these changes
:+1:

2023-06-30 10:07 UTC, Juan-Valle requested changes
Please, review your last git push -f where you tried to add the right github templates.

2023-06-30 10:23 UTC, Juan-Valle approved these changes

2023-06-30 10:26 UTC, merged